# 서버 포트
server:
  port: 20001
---
# 동적 적용
spring:
  devtools:
    livereload:
      enabled: true
---
# Static 정적 리소스 접근
spring:
  resources:
    static-locations: classpath:/static/
    add-mappings: true
  mvc:
    static-path-pattern: /static/**

---
# Oracle Database
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: test
    password: 1234
---
# MyBatis
mybatis:
  type-aliases-package: com.dreamcapsule.project.domain
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true

---
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
